name: Dotfiles Installation

on:
  push:
  schedule:
    - cron: '00 08 * * 2' # Every Tuesday 08:00AM

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]

    steps:
      - name: Clean up installed software
        if: startsWith(matrix.os, 'macos')
        run: |
          brew uninstall --ignore-dependencies --force $(brew list --formula)
          brew uninstall --cask --force $(brew list --cask)
          brew uninstall --cask --force firefox google-chrome
          brew cleanup --prune-prefix
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"

      - name: Install using setup script
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/BinaryHexer/dotfiles/${GITHUB_SHA}/install.sh)"

      - name: Run tests
        if: startsWith(matrix.os, 'macos')
        run: cd "$HOME/.dotfiles"; make test
